### ISSUE TITLE
key_file not being accepted

### ISSUE THREAD

**Issue by kaldrenon** [danryan/spice#15]
Using Spice for the first time, when I do Spice.key_file = "/path/to/key.pem" I am getting the following output:

```
ArgumentError: The file  does not contain a correctly formatted private key.
The key file should begin with '-----BEGIN RSA PRIVATE KEY-----' and end with '-----END RSA PRIVATE KEY-----'
    from /Library/Ruby/Gems/1.8/gems/spice-0.8.0/lib/spice.rb:166:in `assert_valid_key_format!'
    from /Library/Ruby/Gems/1.8/gems/spice-0.8.0/lib/spice.rb:83:in `key_file='
    from (irb):2
```

I am using the same key I've been using for a month to connect to my Chef Server, so I know Ubuntu is happy with the format of my key. Spice seems happy with other keys in my ~/.ssh folder that, as far as I can tell, are identically formatted. Any suggestions?

**Comment by kaldrenon** [comment]
So this may still be an issue for some (I'm not sure), but it turns out I was making a dumb mistake and using a key for the machine Chef Server was on, instead of an admin client key. Everything worked as intended when I changed keys.
