### ISSUE TITLE
Uninitialized constant Chef

### ISSUE THREAD

**Issue by trobrock** [danryan/spice#25]
Is the chef gem required? It seems like it is, but its not specified in the gemspec

``` ruby
irb(main):009:0> Spice.nodes
ArgumentError: can't get const Chef::Node: uninitialized constant Chef
        from /usr/local/opt/rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/json-1.7.5/lib/json/common.rb:44:in `rescue in block in deep_const_get'
        from /usr/local/opt/rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/json-1.7.5/lib/json/common.rb:41:in `block in deep_const_get'
        from /usr/local/opt/rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/json-1.7.5/lib/json/common.rb:36:in `each'
        from /usr/local/opt/rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/json-1.7.5/lib/json/common.rb:36:in `inject'
        from /usr/local/opt/rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/json-1.7.5/lib/json/common.rb:36:in `deep_const_get'
        from /usr/local/opt/rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/json-1.7.5/lib/json/common.rb:155:in `parse'
        from /usr/local/opt/rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/json-1.7.5/lib/json/common.rb:155:in `parse'
        from /usr/local/opt/rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/multi_json-1.3.7/lib/multi_json/adapters/json_common.rb:7:in `load'
        from /usr/local/opt/rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/multi_json-1.3.7/lib/multi_json.rb:96:in `load'
        from /usr/local/opt/rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/spice-1.0.6/lib/spice/response/parse_json.rb:17:in `parse'
        from /usr/local/opt/rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/spice-1.0.6/lib/spice/response/parse_json.rb:23:in `on_complete'
        from /usr/local/opt/rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/faraday-0.8.4/lib/faraday/response.rb:9:in `block in call'
        from /usr/local/opt/rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/faraday-0.8.4/lib/faraday/response.rb:63:in `on_complete'
        from /usr/local/opt/rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/faraday-0.8.4/lib/faraday/response.rb:8:in `call'
        from /usr/local/opt/rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/faraday-0.8.4/lib/faraday/connection.rb:226:in `run_request'
        from /usr/local/opt/rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/spice-1.0.6/lib/spice/request.rb:55:in `request'
        from /usr/local/opt/rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/spice-1.0.6/lib/spice/request.rb:11:in `get'
        from /usr/local/opt/rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/spice-1.0.6/lib/spice/connection/search.rb:26:in `search'
        from /usr/local/opt/rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/spice-1.0.6/lib/spice/connection/nodes.rb:13:in `nodes'
        from /usr/local/opt/rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/spice-1.0.6/lib/spice.rb:20:in `method_missing'
        from (irb):9
```

**Comment by trobrock** [comment]
Solved this with `JSON.create_id = nil` to avoid trying to marshall into objects
