### ISSUE TITLE
Get "read server certificate B: certificate verify failed"

### ISSUE THREAD

**Issue by jesbby** [danryan/spice#27]
Trying to use Spice to talk to 11.4 Chef Server. Running Ruby 2.0.0p247/RVM 1.21.5 on Ubuntu 13.04. Have tried every method I can find to update my ssl cert, but still get:

/home/vagrant/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:918:in `connect': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (Spice::Error::ClientError)
    from /home/vagrant/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:918:in`block in connect'
    from /home/vagrant/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
    from /home/vagrant/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:918:in`connect'
    from /home/vagrant/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
    from /home/vagrant/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:851:in`start'
    from /home/vagrant/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:1367:in `request'
    from /home/vagrant/.rvm/gems/ruby-2.0.0-p247/gems/faraday-0.8.7/lib/faraday/adapter/net_http.rb:75:in`perform_request'
    from /home/vagrant/.rvm/gems/ruby-2.0.0-p247/gems/faraday-0.8.7/lib/faraday/adapter/net_http.rb:38:in `call'
    from /home/vagrant/.rvm/gems/ruby-2.0.0-p247/gems/faraday-0.8.7/lib/faraday/response.rb:8:in`call'
    from /home/vagrant/.rvm/gems/ruby-2.0.0-p247/gems/faraday-0.8.7/lib/faraday/response.rb:8:in `call'
    from /home/vagrant/.rvm/gems/ruby-2.0.0-p247/gems/faraday-0.8.7/lib/faraday/connection.rb:247:in`run_request'
    from /home/vagrant/.rvm/gems/ruby-2.0.0-p247/gems/spice-1.0.6/lib/spice/request.rb:55:in `request'
    from /home/vagrant/.rvm/gems/ruby-2.0.0-p247/gems/spice-1.0.6/lib/spice/request.rb:11:in`get'
    from /home/vagrant/.rvm/gems/ruby-2.0.0-p247/gems/spice-1.0.6/lib/spice/connection/search.rb:34:in `search'
    from /home/vagrant/.rvm/gems/ruby-2.0.0-p247/gems/spice-1.0.6/lib/spice/connection/clients.rb:11:in`clients'
    from /home/vagrant/.rvm/gems/ruby-2.0.0-p247/gems/spice-1.0.6/lib/spice.rb:20:in `method_missing'
    from spice.rb:7:in`<main>'

**Comment by jesbby** [comment]
After further research I don't think this is Spice's fault. Get exactly the same error from Ridley. Spice works fine if I set my Chef server to accept HTTP requests.
